export type Lang = "en" | "zh";

export const dict = {
  en: {
    nav: {
      links: ["How It Works", "Features", "Tech Stack", "Open Source"],
      apiDocs: "API Docs",
      getTheApp: "Get the App",
    },
    hero: {
      headline1: "Find someone to hang out with",
      headline2: "in the mall you're already in.",
      sub: "Post what you want to do in the next hour — a meal, an arcade round, a shopping run. AI matches you with someone at the same venue, plans the first hour, and a small MON deposit keeps you both honest.",
      chips: [
        { icon: "📍", label: "Same-Venue Matching" },
        { icon: "🤖", label: "AI Match + Plan" },
        { icon: "💰", label: "MON Commitment Deposit" },
        { icon: "🎖️", label: "Soulbound Credentials" },
        { icon: "📱", label: "No Seed Phrase" },
      ],
      ctaApp: "Get the App →",
      ctaDocs: "Live API Docs",
      ctaOpen: "★ Open Source",
      phone: {
        location: "📍 Taikoo Li Mall · next 60 min · Dining",
        name: "Lin · 4F, same mall",
        match: "92% match · 7 meetups kept",
        quote:
          "\"Both free until 8pm and both want hotpot. Verified, and has kept every meetup so far.\"",
        pass: "Pass",
        letsGo: "Let's go",
        depositLabel: "Your commitment deposit",
        refundNote: "Refunds on check-in",
      },
    },
    howItWorks: {
      badge: "How It Works",
      title1: "From standing alone in a mall",
      title2: "to actually doing something.",
      sub: "Matching is the easy half. Monad Mate also plans the first hour and makes showing up mean something.",
      steps: [
        {
          n: "01",
          icon: "📱",
          title: "Sign In, No Seed Phrase",
          desc: "Log in with your email or phone. Monad Mate provisions a managed account for you — no seed phrase, no gas prompts. Bring your own MetaMask or Rabby instead if you'd rather self-custody.",
        },
        {
          n: "02",
          icon: "📍",
          title: "Post What You Want, Right Now",
          desc: "Pick the mall or supermarket you're standing in, choose a scene — a meal, an arcade round, a shopping run — and set how long you've got. Matching is limited to that venue and that time window.",
        },
        {
          n: "03",
          icon: "🤖",
          title: "AI Surfaces Who's Actually Nearby",
          desc: "The match agent ranks people at the same venue with an overlapping window and the same intent, factoring shared interests, follow-through history, and safety preferences. Every suggestion comes with a reason.",
        },
        {
          n: "04",
          icon: "🤝",
          title: "Both Sides Confirm",
          desc: "You see verification status and past follow-through before deciding. Either side can pass with no penalty. Only a mutual yes forms a team.",
        },
        {
          n: "05",
          icon: "💰",
          title: "Commit a Small Deposit",
          desc: "Both parties put up a fixed MON deposit through the escrow contract. It's a commitment to your own attendance — not a bet on whether the other person shows.",
        },
        {
          n: "06",
          icon: "⭐",
          title: "Meet, Check In, Earn a Credential",
          desc: "Confirm the meetup with GPS or a QR scan. Deposits return automatically, and a soulbound credential records the venue type, scene, and that you kept your word — never who you met.",
        },
      ],
    },
    features: {
      badge: "Features",
      title1: "Built for the hour",
      title2: "you're actually free.",
      sub: "Every feature exists to close one gap: matching strangers who are in the same place right now, and making sure they both show up.",
      items: [
        {
          icon: "📍",
          title: "Same Venue, Same Hour",
          desc: "Requests are anchored to a specific mall or supermarket and a time window. Candidates must share the venue, the window, and the intent — no cross-city feed padding, and an empty result stays empty.",
          tags: ["Venue-Scoped", "Time Window", "Scene Match"],
          color: "violet",
        },
        {
          icon: "🤖",
          title: "AI Match Agent",
          desc: "Preference embeddings plus follow-through history, habit overlap, window fit, and safety signals. Every candidate ships with the reasons it surfaced, so the ranking is explainable.",
          tags: ["Vector Similarity", "Explainable", "Habit Affinity"],
          color: "purple",
        },
        {
          icon: "📱",
          title: "No Seed Phrase Needed",
          desc: "Email or phone login provisions a managed account — no key management, no gas prompts. Link an external wallet later to take full self-custody whenever you want.",
          tags: ["Managed Wallet", "Gas Sponsored", "Self-Custody Path"],
          color: "pink",
        },
        {
          icon: "💰",
          title: "Commitment Deposit",
          desc: "A fixed MON deposit held in the escrow contract, returned once both sides check in. It binds your own attendance — betting on someone else's behaviour is explicitly out of scope.",
          tags: ["Monad Escrow", "Native MON", "Auto-Refund"],
          color: "coral",
        },
        {
          icon: "🛡️",
          title: "Safety Preferences",
          desc: "Same-gender-only, verified-only, and minimum-reputation filters are hard constraints applied in both directions — a candidate failing them is never shown, not merely ranked lower.",
          tags: ["Hard Filters", "Bidirectional", "Verification Gate"],
          color: "violet",
        },
        {
          icon: "🎖️",
          title: "Soulbound Credentials",
          desc: "Each completed meetup mints a non-transferable credential holding the venue category, scene, time, and outcome. No counterparty identity is ever written on-chain.",
          tags: ["Soulbound", "Privacy-Safe", "Correctable"],
          color: "purple",
        },
        {
          icon: "📊",
          title: "Follow-Through Credit",
          desc: "Credit is built from real attendance records and stays hidden until enough history exists. It describes past follow-through only — never a personal-safety guarantee.",
          tags: ["History-Based", "No Leaderboard", "Disclosed Limits"],
          color: "pink",
        },
        {
          icon: "🚨",
          title: "Reports & Arbitration",
          desc: "Six report categories, repeat-offender detection, and bidirectional blocks. A one-sided claim never auto-convicts — unmatched check-ins go to review instead of an instant penalty.",
          tags: ["Moderation", "Review Queue", "Bidirectional Block"],
          color: "coral",
        },
      ],
    },
    techStack: {
      badge: "Tech Stack",
      title1: "Multi-chain by design.",
      title2: "Accountable by default.",
      sections: [
        {
          category: "Blockchain",
          items: [
            { name: "Monad", desc: "EIP-191 wallet auth, escrow, event log, soulbound credentials" },
            { name: "Foundry", desc: "Escrow, event log, and SBT contracts with forge tests" },
            { name: "Hedera HCS", desc: "Immutable audit log for attestations" },
            { name: "Base (Coinbase)", desc: "x402 HTTP payment protocol" },
          ],
        },
        {
          category: "Backend",
          items: [
            { name: "FastAPI", desc: "30 service classes, 50+ endpoints" },
            { name: "SQLAlchemy 2.0", desc: "17 ORM models, PgBouncer connection pooling" },
            { name: "Celery + Redis", desc: "Deposit review, match expiry, credit refresh" },
            { name: "PostgreSQL", desc: "sm_ prefixed schema, full pytest suite" },
          ],
        },
        {
          category: "AI / Infra",
          items: [
            { name: "DeepSeek-R1 / bge", desc: "Local LLM icebreakers + 1024-dim semantic matching" },
            { name: "Ollama + Xinference", desc: "Self-hosted LLM inference and embedding services" },
            { name: "Hedera HCS", desc: "Tamper-proof audit log for safety decisions" },
            { name: "Preference Memory", desc: "Embedding-backed user preference vectors" },
          ],
        },
        {
          category: "Mobile / DApp",
          items: [
            { name: "Progressive Web App", desc: "Add to Home Screen, installable on any mobile browser" },
            { name: "Managed accounts", desc: "Email or phone login, no seed phrase or gas" },
            { name: "MetaMask / Rabby", desc: "Self-custody sign-in for wallet users" },
            { name: "x402 Protocol", desc: "USDC payment gate on Base" },
          ],
        },
      ],
      stats: [
        { value: "451", label: "Tests passing", sub: "backend suite" },
        { value: "50+", label: "API endpoints", sub: "12 domains" },
        { value: "30", label: "Service classes", sub: "fully tested" },
        { value: "3", label: "Solidity contracts", sub: "ready for Monad testnet" },
      ],
    },
    download: {
      badge: "Get Monad Mate",
      title1: "Ready to find someone",
      title2: "for the next hour?",
      sub: "Monad Mate runs in the browser — no app store required. Sign in with your email or connect a wallet, whichever you prefer.",
      webTitle: "Web App",
      webDesc: "Open in any browser. Email login, or connect MetaMask or Rabby. No install needed.",
      webBtn: "Open Web App →",
      apkTitle: "Android APK",
      apkSoon: "Coming Soon",
      apkDesc: "Sideload build for testers. Same dApp, packaged for Android.",
      apkBtn: "Available after review",
      pwaTitle: "Install as PWA",
      pwaDesc: "Open in mobile browser → \"Add to Home Screen\" for a native-like experience.",
      pwaBtn: "Open on Mobile →",
      compatTitle: "Sign-in options & networks",
      compat: ["📧 Email / Phone", "🟣 MetaMask", "🔵 Rabby", "⚡ Monad Testnet", "🌐 Any Mobile Browser"],
    },
    openSource: {
      badge: "Open Source",
      title1: "Built for the ecosystem.",
      title2: "Free to fork.",
      sub: "Monad Mate is MIT licensed. The primitives we built — deposit gating, soulbound credentials, reputation decay — are being extracted as standalone packages.",
      contributions: [
        {
          icon: "🎖️",
          title: "Soulbound Credential Contract",
          desc: "A fulfilment SBT where every transfer path reverts, metadata carries no counterparty identity, and arbitration can still amend an outcome. Reusable for any app recording real-world follow-through.",
        },
        {
          icon: "🏗️",
          title: "Commitment Deposit Escrow",
          desc: "Open-source escrow keyed by (staker, room_id). Reusable for any deposit-gated Monad app. Built with Foundry, deployable to Monad testnet in one command.",
        },
        {
          icon: "📱",
          title: "Managed Wallet Onboarding",
          desc: "Deterministic key derivation for seed-phrase-free accounts, with keys never persisted, single-use login codes, disclosed custody, and a signature-verified exit to self-custody.",
        },
        {
          icon: "🧠",
          title: "Pure-Python Preference Embeddings",
          desc: "45-term bag-of-words vocabulary, L2-normalised, zero numpy dependency. Embeddable preference memory for resource-constrained environments.",
        },
      ],
      packagesTitle: "Published Packages",
      packages: [
        {
          name: "monadmate-stake-sdk",
          install: "pip install monadmate-stake-sdk",
          pypiUrl: "https://pypi.org/project/monadmate-stake-sdk/",
          desc: "Stake-gated access control for any Monad dApp. Require MON escrow before DMs, room entry, or any action.",
        },
        {
          name: "monadmate-reputation",
          install: "pip install monadmate-reputation",
          pypiUrl: "https://pypi.org/project/monadmate-reputation/",
          desc: "5-dimension reputation engine with time decay and Hedera HCS anchoring. Portable trust scoring for Web3 social apps.",
        },
        {
          name: "monadmate-x402",
          install: "pip install monadmate-x402",
          pypiUrl: "https://pypi.org/project/monadmate-x402/",
          desc: "FastAPI middleware for Coinbase x402 HTTP-native USDC payments on Base. Drop-in dependency for any FastAPI endpoint.",
        },
      ],
      githubCta: "View on GitHub",
      licenseNote: "MIT License · 451 tests passing",
    },
    footer: {
      apiDocs: "API Docs",
      contributing: "Contributing",
      license: "MIT License",
      builtFor: "Built for EasyA × Consensus Miami 2026 · Monad + Hedera + Base",
      live: "Live ↗",
    },
  },

  zh: {
    nav: {
      links: ["运作方式", "功能特性", "技术栈", "开源"],
      apiDocs: "API 文档",
      getTheApp: "进入应用",
    },
    hero: {
      headline1: "在你所在的商场里",
      headline2: "找到此刻同行的人。",
      sub: "发布你接下来一小时想做的事——吃顿饭、打一局电玩、逛个街。AI 为你匹配同一场馆的人，规划第一个小时，小额 MON 押金让双方都守约。",
      chips: [
        { icon: "📍", label: "同场馆匹配" },
        { icon: "🤖", label: "AI 匹配 + 规划" },
        { icon: "💰", label: "MON 履约押金" },
        { icon: "🎖️", label: "灵魂绑定凭证" },
        { icon: "📱", label: "无需助记词" },
      ],
      ctaApp: "进入应用 →",
      ctaDocs: "API 文档",
      ctaOpen: "★ 开源项目",
      phone: {
        location: "📍 太古里商场 · 未来 60 分钟 · 美餐",
        name: "小林 · 4楼 · 同商场",
        match: "92% 匹配 · 7 次守约",
        quote: "\"都在 8 点前有空，都想吃火锅。已实名验证，至今每次约见都守约。\"",
        pass: "略过",
        letsGo: "走起",
        depositLabel: "你的履约押金",
        refundNote: "打卡后自动退还",
      },
    },
    howItWorks: {
      badge: "运作方式",
      title1: "从一个人逛商场",
      title2: "到真正有人同行。",
      sub: "匹配只是开始。Monad Mate 还会规划你们的第一小时，让守约变得有意义。",
      steps: [
        {
          n: "01",
          icon: "📱",
          title: "登录，无需助记词",
          desc: "邮箱或手机号即可登录，Monad Mate 自动为你创建托管账户——没有助记词、没有 Gas 弹窗。想自己保管资产？随时可绑定 MetaMask 或 Rabby 外部钱包。",
        },
        {
          n: "02",
          icon: "📍",
          title: "发布你此刻的需求",
          desc: "选择你所在的商场或超市，挑选场景——吃饭、电玩、逛街——设定空闲时长。匹配只限于同一场馆、同一时间窗内的人。",
        },
        {
          n: "03",
          icon: "🤖",
          title: "AI 找出真正在附近的人",
          desc: "匹配代理对同场馆、时间窗重叠、意向相同的人进行排序，综合共同兴趣、履约历史和安全偏好。每条推荐都附带理由。",
        },
        {
          n: "04",
          icon: "🤝",
          title: "双方确认",
          desc: "决定前可查看对方的验证状态和历史履约记录。任何一方都可无成本略过，只有双方都同意才组队成功。",
        },
        {
          n: "05",
          icon: "💰",
          title: "小额押金表达诚意",
          desc: "双方通过托管合约各存入固定 MON 押金。这是对自己出席的承诺——而不是赌对方会不会来。",
        },
        {
          n: "06",
          icon: "⭐",
          title: "见面、打卡、赢得凭证",
          desc: "通过 GPS 或扫码确认见面。押金自动退还，灵魂绑定凭证记录场馆类型、场景与你的守约事实——绝不记录你见了谁。",
        },
      ],
    },
    features: {
      badge: "功能特性",
      title1: "为你真正空闲的",
      title2: "那一小时而设计。",
      sub: "每个功能只为解决一件事：匹配此刻同处一地的陌生人，并确保双方都会赴约。",
      items: [
        {
          icon: "📍",
          title: "同场馆，同小时",
          desc: "请求锚定在特定商场或超市与时间窗内。候选人必须共享场馆、时间窗与意向——没有跨城信息流注水，没有结果就是没有结果。",
          tags: ["场馆限定", "时间窗", "场景匹配"],
          color: "violet",
        },
        {
          icon: "🤖",
          title: "AI 匹配代理",
          desc: "偏好向量结合履约历史、作息重合、时间窗契合与安全信号。每位候选人都附带推荐理由，排序可解释。",
          tags: ["向量相似", "可解释", "作息契合"],
          color: "purple",
        },
        {
          icon: "📱",
          title: "无需助记词",
          desc: "邮箱或手机登录即获得托管账户——无需管理密钥、无 Gas 弹窗。之后可随时绑定外部钱包，完全自主托管。",
          tags: ["托管钱包", "代付 Gas", "自托管通道"],
          color: "pink",
        },
        {
          icon: "💰",
          title: "履约押金",
          desc: "固定 MON 押金存入托管合约，双方打卡后自动退还。它约束的是你自己的出席——押注他人行为明确不在范围内。",
          tags: ["Monad 托管", "原生 MON", "自动退还"],
          color: "coral",
        },
        {
          icon: "🛡️",
          title: "安全偏好",
          desc: "仅同性别、仅已验证、最低信誉分等过滤条件是双向生效的硬约束——不合格的候选人根本不会展示，而不只是排名靠后。",
          tags: ["硬性过滤", "双向生效", "验证门槛"],
          color: "violet",
        },
        {
          icon: "🎖️",
          title: "灵魂绑定凭证",
          desc: "每次完成的约见铸造一枚不可转让凭证，记录场馆类别、场景、时间与结果。链上永不写入对方身份。",
          tags: ["灵魂绑定", "隐私安全", "可修正"],
          color: "purple",
        },
        {
          icon: "📊",
          title: "履约信用",
          desc: "信用由真实出席记录构成，历史不足时对外隐藏。它只描述过往履约——绝非人身安全保证。",
          tags: ["基于历史", "无排行榜", "边界公开"],
          color: "pink",
        },
        {
          icon: "🚨",
          title: "举报与仲裁",
          desc: "六类举报、惯犯识别、双向拉黑。单方举报绝不自动定罪——未匹配的打卡进入复核而非直接处罚。",
          tags: ["审核队列", "人工复核", "双向拉黑"],
          color: "coral",
        },
      ],
    },
    techStack: {
      badge: "技术栈",
      title1: "多链架构设计，",
      title2: "天生的可信履约。",
      sections: [
        {
          category: "区块链",
          items: [
            { name: "Monad", desc: "EIP-191 钱包认证、托管合约、事件日志、灵魂绑定凭证" },
            { name: "Foundry", desc: "托管/事件日志/SBT 合约，含 forge 测试" },
            { name: "Hedera HCS", desc: "不可篡改的存证审计日志" },
            { name: "Base (Coinbase)", desc: "x402 HTTP 支付协议" },
          ],
        },
        {
          category: "后端",
          items: [
            { name: "FastAPI", desc: "30 个服务类，50+ 接口" },
            { name: "SQLAlchemy 2.0", desc: "17 个 ORM 模型，PgBouncer 连接池" },
            { name: "Celery + Redis", desc: "押金复核、匹配过期、信用刷新" },
            { name: "PostgreSQL", desc: "sm_ 前缀 schema，完整 pytest 套件" },
          ],
        },
        {
          category: "AI / 基础设施",
          items: [
            { name: "DeepSeek-R1 / bge", desc: "本地 LLM 破冰语 + 1024 维语义匹配" },
            { name: "Ollama + Xinference", desc: "自托管 LLM 推理与向量服务" },
            { name: "Hedera HCS", desc: "安全决策防篡改审计日志" },
            { name: "偏好记忆", desc: "基于向量嵌入的用户偏好表征" },
          ],
        },
        {
          category: "移动 / DApp",
          items: [
            { name: "渐进式 Web 应用", desc: "添加到主屏幕，任意移动浏览器可安装" },
            { name: "托管账户", desc: "邮箱/手机登录，无助记词无 Gas" },
            { name: "MetaMask / Rabby", desc: "面向钱包用户的自托管登录" },
            { name: "x402 协议", desc: "Base 链 USDC 支付闸门" },
          ],
        },
      ],
      stats: [
        { value: "451", label: "测试通过", sub: "后端套件" },
        { value: "50+", label: "API 接口", sub: "12 个领域" },
        { value: "30", label: "服务类", sub: "全覆盖测试" },
        { value: "3", label: "Solidity 合约", sub: "可部署 Monad 测试网" },
      ],
    },
    download: {
      badge: "获取 Monad Mate",
      title1: "准备好找到下一小时的",
      title2: "同行者了吗？",
      sub: "Monad Mate 直接在浏览器中运行——无需应用商店。邮箱登录或连接钱包，随你喜欢。",
      webTitle: "网页应用",
      webDesc: "任意浏览器打开。邮箱登录，或连接 MetaMask / Rabby。无需安装。",
      webBtn: "打开网页应用 →",
      apkTitle: "安卓 APK",
      apkSoon: "即将推出",
      apkDesc: "测试者侧载版本。同一 dApp，打包为安卓应用。",
      apkBtn: "审核通过后开放",
      pwaTitle: "安装为 PWA",
      pwaDesc: "移动浏览器打开 → 「添加到主屏幕」，获得类原生体验。",
      pwaBtn: "手机上打开 →",
      compatTitle: "登录方式与网络",
      compat: ["📧 邮箱/手机", "🟣 MetaMask", "🔵 Rabby", "⚡ Monad 测试网", "🌐 任意移动浏览器"],
    },
    openSource: {
      badge: "开源",
      title1: "为生态而建，",
      title2: "随意 Fork。",
      sub: "Monad Mate 采用 MIT 协议。我们构建的基础组件——押金门槛、灵魂绑定凭证、信誉衰减——正被抽取为独立软件包。",
      contributions: [
        {
          icon: "🎖️",
          title: "灵魂绑定凭证合约",
          desc: "履约 SBT：所有转账路径都会回退，元数据不含对方身份，仲裁仍可修正结果。任何记录真实履约的应用都可复用。",
        },
        {
          icon: "🏗️",
          title: "履约押金托管",
          desc: "以 (staker, room_id) 为键的开源托管合约。任何押金门槛的 Monad 应用都可复用。Foundry 构建，一条命令部署至 Monad 测试网。",
        },
        {
          icon: "📱",
          title: "托管钱包开户",
          desc: "确定性密钥派生实现无助记词账户：密钥永不落盘、登录码一次性使用、托管透明、签名验证的自托管出口。",
        },
        {
          icon: "🧠",
          title: "纯 Python 偏好向量",
          desc: "45 词袋词汇表、L2 归一化、零 numpy 依赖。适用于资源受限环境的可嵌入式偏好记忆。",
        },
      ],
      packagesTitle: "已发布软件包",
      packages: [
        {
          name: "monadmate-stake-sdk",
          install: "pip install monadmate-stake-sdk",
          pypiUrl: "https://pypi.org/project/monadmate-stake-sdk/",
          desc: "任何 Monad dApp 可用的押金门控访问。私信、进房或任意动作前要求 MON 托管。",
        },
        {
          name: "monadmate-reputation",
          install: "pip install monadmate-reputation",
          pypiUrl: "https://pypi.org/project/monadmate-reputation/",
          desc: "五维信誉引擎，含时间衰减与 Hedera HCS 锚定。Web3 社交应用可移植的信任评分。",
        },
        {
          name: "monadmate-x402",
          install: "pip install monadmate-x402",
          pypiUrl: "https://pypi.org/project/monadmate-x402/",
          desc: "Base 链上 Coinbase x402 HTTP 原生 USDC 支付的 FastAPI 中间件。任何 FastAPI 端点即插即用。",
        },
      ],
      githubCta: "在 GitHub 查看",
      licenseNote: "MIT 协议 · 451 项测试通过",
    },
    footer: {
      apiDocs: "API 文档",
      contributing: "参与贡献",
      license: "MIT 协议",
      builtFor: "EasyA × Consensus Miami 2026 参赛作品 · Monad + Hedera + Base",
      live: "在线 ↗",
    },
  },
};
