from pydantic import BaseModel, Field
from typing import Dict, List, Optional
from datetime import datetime
from uuid import UUID

from ..models.meetup_plan import PlanSource


class ItineraryStep(BaseModel):
    minute: int = Field(..., description="Offset in minutes from the meetup start.")
    title: str
    detail: str = ""


class MiniGame(BaseModel):
    name: str
    how_to_play: str


class MeetupPlanResponse(BaseModel):
    id: UUID
    match_id: UUID
    venue_name: Optional[str]
    venue_type: Optional[str]
    scene: Optional[str]
    duration_minutes: Optional[int]
    party_size: Optional[int]
    icebreakers: List[str]
    itinerary: List[ItineraryStep]
    mini_game: Dict[str, str]
    shared_interests: List[str]
    source: PlanSource = Field(
        ..., description="`llm` when generated by the model, `template` on fallback."
    )
    adopted: bool
    created_at: datetime

    class Config:
        from_attributes = True
