import type { Metadata } from "next";
import "./globals.css";

const SITE_URL = "https://monad-mate-landing-production.up.railway.app";

export const metadata: Metadata = {
  title: "Monad Mate — Skin in the Game Social on Monad",
  description:
    "Stake MON to DM, match, and meet on Monad. No-shows get slashed. AI matchmaking with 768-dim embeddings. GPS-verified meetups. Economic accountability replaces swipe culture.",
  keywords: [
    "Monad social app",
    "stake-to-interact",
    "Web3 dating",
    "MON stake",
    "AI matchmaking",
    "Monad dApp",
    "Monad testnet",
    "Hedera HCS",
    "x402 payments",
    "ZeroDB",
  ],
  metadataBase: new URL(SITE_URL),
  alternates: {
    canonical: "/",
  },
  openGraph: {
    title: "Monad Mate — Skin in the Game Social on Monad",
    description:
      "Stake MON to DM, match, and meet. No-shows get slashed. Genuine connections earn reputation. AI matchmaking powered by AINative.",
    siteName: "Monad Mate",
    type: "website",
    url: SITE_URL,
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: "Monad Mate — Skin in the Game Social on Monad",
    description:
      "Stake MON to DM, match, and meet. No-shows get slashed. Genuine connections earn reputation. Built on Monad.",
    creator: "@HankGrimm",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
    },
  },
  manifest: "/manifest.json",
};

export const viewport = {
  themeColor: "#7C3AED",
};

const jsonLd = [
  {
    "@context": "https://schema.org",
    "@type": "WebSite",
    "name": "Monad Mate",
    "url": "https://monad-mate-landing-production.up.railway.app",
    "description": "Stake MON to DM, match, and meet. No-shows get slashed on Monad.",
  },
  {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    "name": "Monad Mate",
    "applicationCategory": "SocialNetworkingApplication",
    "operatingSystem": "Web, iOS, Android",
    "description": "Trust-based social dApp on Monad. Stake MON to DM, match, and meet. No-shows get slashed. AI matchmaking powered by AINative.",
    "url": "https://monad-mate-landing-production.up.railway.app",
    "softwareVersion": "0.1.0",
    "offers": {
      "@type": "Offer",
      "price": "0",
      "priceCurrency": "USD",
      "description": "Free to use on Monad testnet"
    },
    "featureList": [
      "Stake-to-interact (DM, room, meetup)",
      "Automatic slashing for no-shows",
      "AI-powered matchmaking",
      "GPS-verified meetup attestation",
      "Moment NFT minting",
      "MON gifting",
      "Coinbase x402 USDC payments",
      "5-dimension reputation system"
    ],
    "creator": {
      "@type": "Person",
      "name": "HankGrimm",
      "url": "https://github.com/HankGrimm"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "Person",
    "name": "HankGrimm",
    "url": "https://github.com/HankGrimm",
    "description": "Builder of Monad Mate — stake-to-interact social dApp on Monad",
    "contactPoint": {
      "@type": "ContactPoint",
      "email": "HankGrimm91@gmail.com"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "mainEntity": [
      {
        "@type": "Question",
        "name": "What is staking in Monad Mate?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Staking means locking a small amount of MON on Monad before you can DM someone, enter a room, or propose a meetup. It creates economic accountability — you have skin in the game."
        }
      },
      {
        "@type": "Question",
        "name": "What happens if I no-show a meetup?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Your stake is slashed — 50% on the first offense, escalating with each subsequent no-show (0.5x multiplier per offense, up to 3x cap). Harassment and fake profiles result in 100% slash."
        }
      },
      {
        "@type": "Question",
        "name": "How does AI matchmaking work?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Monad Mate uses AINative's BAAI/bge-base-en-v1.5 embeddings to encode user preferences into 768-dimensional vectors stored in ZeroDB. Match requests trigger cosine similarity search to find compatible users, and intro messages are generated by llama-3.3-70b hosted on AINative."
        }
      },
      {
        "@type": "Question",
        "name": "What is a Moment NFT?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "After a confirmed meetup (GPS-verified by both parties), you can mint a Moment NFT on Monad as a commemorative proof of connection."
        }
      }
    ]
  }
]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        <meta name="ai-content-declaration" content="human-authored with AI assistance" />
        <meta name="ai-training" content="allowed" />
        <link rel="agent-guide" href="/agent.md" />
        <link rel="agents-guide" href="/agents.md" />
        {jsonLd.map((schema, i) => (
          <script
            key={i}
            type="application/ld+json"
            dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
          />
        ))}
      </head>
      <body>{children}</body>
    </html>
  );
}
